### ISSUE TITLE
Update code to work with newer versions of Kokkos develop

### ISSUE THREAD

**Issue by nphtan** [kokkos/kokkos-resilience#40]
A recent commit (4dced25118a9fa5021de7e8cf076154cf9681e26) changed the names for some of the internal OpenMP files. Kokkos resilience will need some updates to rename a few header includes.
*  Kokkos_OpenMP_Exec -> Kokkos_OpenMP_Instance
*  Kokkos::Impl::OpenMPExec -> Kokkos::Impl::OpenMPInternal

There are also some issues in some of the tests (TestOpenMPResilientExecution.cpp). I don't see any recent changes that could have caused the problem other than some magic number changes.

/home/nphtan/kokkos/build/install/include/impl/Kokkos_Profiling_Interface.hpp(126): error: class "Kokkos::Tools::Experimental::DeviceTypeTraits<KokkosResilience::ResOpenMP>" has no member "device_id"
           (DeviceTypeTraits<ExecutionSpace>::device_id(space)
                                              ^
          detected during:
            instantiation of "uint32_t={__uint32_t={unsigned int}} Kokkos::Tools::Experimental::device_id(const ExecutionSpace &) [with ExecutionSpace=KokkosResilience::ResOpenMP]" at line 371 of "/home/nphtan/kokkos/build/install/include/impl/Kokkos_Tools_Generic.hpp"
            instantiation of "void Kokkos::Tools::Impl::begin_parallel_for(ExecPolicy &, FunctorType &, const std::string &, uint64_t={__uint64_t={unsigned long}} &) [with ExecPolicy=range_policy, FunctorType=const lambda [](int)->void]" at line 162 of "/home/nphtan/kokkos/build/install/include/Kokkos_Parallel.hpp"
            instantiation of "void Kokkos::parallel_for(const ExecPolicy &, const FunctorType &, const std::string &, std::enable_if_t<Kokkos::is_execution_policy<ExecPolicy>::value, void> *) [with ExecPolicy=range_policy, FunctorType=lambda [](int)->void]" at line 113 of "/home/nphtan/kokkos-resilience/tests/TestOpenMPResilientExecution.cpp"

compilation aborted for /home/nphtan/kokkos-resilience/tests/TestOpenMPResilientExecution.cpp (code 2)
make[2]: *** [tests/CMakeFiles/resilience_tests.dir/build.make:134: tests/CMakeFiles/resilience_tests.dir/TestOpenMPResilientExecution.cpp.o] Error 2
make[1]: *** [CMakeFiles/Makefile2:573: tests/CMakeFiles/resilience_tests.dir/all] Error 2
make: *** [Makefile:160: all] Error 2

**Comment by nmm0** [comment]
We were able to reproduce this (and a few other issues due to some internal changes Kokkos made), we are working on a fix
