### ISSUE TITLE
Build error for Kokkos::Cuda backend

### ISSUE THREAD

**Issue by pkestene** [kokkos/kokkos-resilience#50]
I'm trying to build current main branch against kokkos with cuda backend activated.

I've encountered at least two errors for which I would need help:

1. about `Kokkos_TrackDuplicates.hpp` 
```shell
[ 48%] Building CXX object tests/CMakeFiles/resilience_tests.dir/TestResilience.cpp.o
In file included from /data/pkestene/install/trilinos/kokkos/github/kokkos-resilience_pk/tests/TestResilience.cpp:45:
/data/pkestene/install/trilinos/kokkos/github/kokkos-resilience_pk/src/resilience/cuda/ResCudaSpace.hpp:47:10: fatal error: impl/Kokkos_TrackDuplicates.hpp: No such file or directory
   47 | #include <impl/Kokkos_TrackDuplicates.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [tests/CMakeFiles/resilience_tests.dir/build.make:90: tests/CMakeFiles/resilience_tests.dir/TestResilience.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:485: tests/CMakeFiles/resilience_tests.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
```
I'm not able to find header `Kokkos_TrackDuplicates.hpp` in kokkos sources even with git grep.

2. about header `impl/Kokkos_Tags.hpp`
```shell
[ 46%] Building CXX object tests/CMakeFiles/resilience_tests.dir/TestResilience.cpp.o
In file included from /data/pkestene/install/trilinos/kokkos/github/kokkos-resilience_pk/tests/TestResilience.cpp:46:
/data/pkestene/install/trilinos/kokkos/github/kokkos-resilience_pk/src/resilience/cuda/ResCuda.hpp:61:10: fatal error: impl/Kokkos_Tags.hpp: No such file or directory
   61 | #include <impl/Kokkos_Tags.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```
header `impl/Kokkos_Tags.hpp` exists in Kokkos sources, but it is not installed anymore.

These errors are trigger when I use kokkos 4.1.00

Which version / git hash of Kokkos do you recommend ?

**Comment by nmm0** [comment]
Thanks for reporting this. Quick question -- are you intending to use Cuda Resilient Execution Spaces? They are currently still very much work in progress. The build script unfortunately enables them automatically, so I can make a fix to turn them off.
